declare module "*.jpg";
declare module "*.JPG";
declare module "*.jpeg";
declare module "*.png";
declare module "*.mp4";
declare module "*.svg";
declare module "*.wav";
declare module "*.mov";
declare module "*.webp";
